### ISSUE TITLE
superscript und subscript

### ISSUE THREAD

**Issue by tbaddade** [jdlx/rex_markitup#3]
Scheint noch nicht dabei zu sein. Notation wäre:

```
^superscript^    ->     <sup>superscript</sup>
~subscript~    ->     <sub>subscript</sub>
```

**Comment by jdlx** [comment]
Ist funktional drin .. per `sub` bzw. `sup` .. fehlen aber noch passende icons.. dafür hab ich grad keine zeit -> in 3 wochen ..

**Comment by jdlx** [comment]
see: 0e8085f734b64b0d683ce1ced417f9f6bd285704 & b9046b74283d8e6b4709ed0fb10570cabf3380c6

**Comment by jdlx** [comment]
Wer macht icons für die buttons? Grad keine Zeit.. bitte per pm melden, dann gibts das .PSD fürs sprite..

**Comment by jdlx** [comment]
fixed per 86788882933972eecd7eb293884fb6d119d04461

**Comment by jdlx** [comment]
THX @ oli kreischer für icons..
